### ISSUE TITLE
Missing receiver metadata proj 156

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/ErrorLog#34] opened 2018-01-24 16:51 UTC
There are detections for project 156 that have no receiver info, not even serial number or gps.  These detections are essentially useless - I think I've brought this up before, but why would serial number be missing?  Example: hitID 20320479 and 20320480, both from runID 1656996 and batchID 5593.  Also hitIDs20328431 and 20328432, both from runID 1660837 and batch 5595

I think related to: https://github.com/MotusDev/ErrorLog/issues/32

**Comment by cjardine-bsc** [comment] 2018-01-24 22:03
The problem is that that receiver is not registered to any project (serno = Lotek-D000426 ) therefore it was not showing up in vwR_Metadata_for_receivers_recvDeps based on it's deviceID since this query was based on inner joins. 

SELECT b.id as deployID,a.project_id as projectID,a.receiverID as serno, c.receiver_type as receiverType,
c.id as deviceID,d.descr as status, b.name, f.name as siteName, b.fixture_type as fixtureType, b.latitude, b.longitude, elevation, cast(g.is_mobile as tinyint) as isMobile, dbo.datetime2ts(b.dt_start) AS tsStart, dbo.datetime2ts(b.dt_end) AS tsEnd, e.accessLevel, e.is_private_sensor 
FROM sensors a 
LEFT JOIN sensors_hash_keys c on a.receiverID = c.receiverID
INNER JOIN sensor_deployments b on a.id = b.sensor_id
INNER JOIN lk_deployment_status d on b.status=d.status 
INNER JOIN vwProjectsSecurables e on a.project_id = e.project_id AND e.securable = 'receivers_deployments'
LEFT JOIN sensor_sites f on b.site_id = f.id 
LEFT JOIN lk_fixture_type g on b.fixture_type=g.fixture_type 

For now, I've changed this query to include left joins so that sensors not registered to projects are included. Although they are missing all metadata. 

SELECT b.id as deployID,a.project_id as projectID,a.receiverID as serno, c.receiver_type as receiverType,
c.id as deviceID,d.descr as status, b.name, f.name as siteName, b.fixture_type as fixtureType, b.latitude, b.longitude, elevation,cast(g.is_mobile as tinyint) as isMobile, dbo.datetime2ts(b.dt_start) AS tsStart, dbo.datetime2ts(b.dt_end) AS tsEnd, e.accessLevel, e.is_private_sensor 
FROM sensors_hash_keys c
LEFT JOIN sensors a on a.receiverID = c.receiverID
LEFT JOIN sensor_deployments b on a.id = b.sensor_id
LEFT JOIN lk_deployment_status d on b.status=d.status 
LEFT JOIN vwProjectsSecurables e on a.project_id = e.project_id AND e.securable = 'receivers_deployments'
LEFT JOIN sensor_sites f on b.site_id = f.id 
LEFT JOIN lk_fixture_type g on b.fixture_type=g.fixture_type 

I've done the same for vwR_Metadata_for_receivers_antDeps

That allows users to at least see the serial number for sensors that detect their tags. However it does not give us a way to determine which project this receiver belongs to and ask for missing deployment metadata through the notification center. 

I think we need to either: 

1. Not allow users to upload files for sernos that are not registered to their project. Returning an error asking users to register the receiver to their project.  
2. Change the API serno registration process so that in additional to writing to sensor_hash_keys it registers the receiver to the project the user is registered to (*don't know how to address users registered to multiple projects) 

Actually, I just looked at prAPIImportSensorsTransfer and it was doing number 2 above, but I think this proc is no longer being used since it still heavily references status and api_import_sensor is empty and bt_api_import_sensor only has test data. 

I think the currently process is only using prInsertSensorsHashKeys, John  isn't passing a projectID to this. Which is probably because a user can be registered to more than one project. That lends support to option 1 above, however the fact that sensor processing is routed through John's server means we can't run the check in real-time. This is something we'll need to add once/if we move the upload tool to motus.org. 

As it stands, since the gps records for these batches do not contain any geo-referencing information, and we don't know what project this receiver belongs to we're not able to resolve this issue, or flag it to a user as missing metadata. So we have 200k orphaned hits from this receiver alone. 

OH! We have a record of the user that uploaded this data in sg_batches. HUZZAH! It looks like only new batches have this information, but at least it gives us a way to follow up with users on some of this. 

Zoe, the following users have uploaded data for sensors that have not been registered to a projects. 

motusUserID: 233 233 587 2340 2435 2435 2435 2435 2682

I've added a new error to the notification center (sandbox) that will alert users to this issue. Since the notification center is project based the error is being returned for all projects that the user is registered to. Jeremy, I've sent the text around this error to Zoe for her review, I'll forward it to you for translation once Zoe's happy and we can move this to the live site. 

However, we still have six device IDs that have hits, are not registered to any project and the motusUserID field in sg_batches is NULL. 

915 912 487 508 505 772

I'll wait for feedback on this post from Denis before taking next steps, but I think we'll need to ask John if he has any additional information on batches for these device IDs so we can try and get them assigned to projects. As long as all new batches coming in contain a motusUserID we at least have a means of flagging these issues to users going forward. 

In a related vein, does anyone have any objections to me retiring prAPIImportSensors, prAPIImportSensorsTransfer, and api_import_sensors to the old schema to clean up the DB?

I hope you've enjoyed this merry trip down the motus-rabbit-hole. Sorry there wasn't a tea party ;)

**Comment by denislepage** [comment] 2018-01-24 22:59
There are several things here.


1)      I think there was a bug in John’s code that he found/fixed(?) recently that affected the userID field. I don’t remember the details or know whether this explains the few missing ones and/or the missing project registrations. I was under the impression that John was registering all receivers to a project though his upload process, but I could be wrong. Our new upload tool will need to do so.


2)      The view: The left join might be the correct way to deal with the R view, but it doesn’t really change anything, other than provide an empty record? Is this because the receiver wasn’t registered by John (with hash key), or that the receiver wasn’t in a/any project? I guess both options are possible. If they are not in any project, then I don’t think the data should be returned, since authentication is based on project. If the receiver isn’t in sensors_hash_keys, there shouldn’t be any data coming from John because they would have no device ID, though we could potentially at least return the metadata. The original view allowed for that, but not the modified one.

While It could make sense to return a row in recv, I don’t see a benefit in returning an empty record in recvDeps. We would likely rather modify the view in R to a LEFT JOIN, if that is the problem. Careful not to modify things too quickly here, as I am not sure I want those receivers to show up within deployments as empty.


3)      The ideal way to do registration:

If we can read the serial number out of the file during the upload (once we have it working on Motus), then we would be able to add new receivers ourselves. I am not sure John is still needing to generate hash keys, but we can at the very least add the receiver to sensors. Ensuring that the serial number matches what John will use is essential to avoid mismatches. That means being able to read the serial directly out of the data files ourselves AND using the same pattern for assigning the serial number (adding SG/Lotek prefix, etc.).

Ideally, if we could also read the range of timestamps from the file, we could check against existing deployments and/or prompt the user to create new ones.

Given the different file formats and origins, I think we need to assume that we can’t easily read the file header before it is fully uploaded.

The detection file upload process should ideally be as follow:


-          People upload a file or a set of files and must identify a receiver project.

-          When upload is complete (of a file or the batch), if possible, read the components that we can use to match with deployments: serial number, start and end ts, antennas port numbers.

-          We try to match the files to individual deployment(s). There may be some cases where a file matches more than 1 deployment. User input shouldn’t be needed for those matched, but they should be presented with easy options to 1) add the receiver(s) to their project, 2) modify any existing deployment that is wrong (link to deployment page?), and also create new deployments, pre-populated with the information that we can gather from the files.

-          once the confirm those details(only then?), we would contact SG data server to indicate that a new file is ready.

Something like that….

If we can’t read the info from the file, at the very least the serial number, we’ll need to come up with plan B.

We should check with John if needed what file formats (e.g. compression) are supported.


4)      The prAPI procs. I don’t know. There’s been a few instances where the API 1.0 broke because of changes that we have made in the database recently. We’re trying to move away from using API 1.0, but we still need to check the Java code for any use of the procs you are mentioning.

**Comment by cjardine-bsc** [comment] 2018-01-24 23:28
1. Of 114324 batches 103079 do not have MotusUserID, so it's an extensive issue. The most recent batches IDs do not have motusUserID. We should make sure this is being pushed to us. 

I was under the same impression that John was registering receivers to a project, however receivers are showing up in sensors_hash_keys and not in sensors.  Looking at prAPIImportSensors, it looks defunct, so I don't think John is writing to the sensors table any longer. I think he's just using prInsertSensorsHashKeys. Since he's not passing this a user or project I can't alter it to write to sensors without some changes from John/Paul. 

2. The change to the view provides the serial ID of the receiver instead of a completely blank record. This isn't hugely useful to the end user UNLESS the receiver happens to belong to that project. Then it acts to alert them to their missing metadata. It's also clearer to the user that this is an issue of missing metadata, not an error in tagme. 

These errors don't have anything to do with missing registrations to sensors_hash_keys. That's covered in the notification center. These issues are arising because the receiver was registered to sensor_hash_keys but not to sensors. These do have device IDs. 

In this case we are returning metadata for sensors that a tag was detected on when tagme is run for a project. So there isn't authentication based on project from the receiver. I'm not sure I see an authentication issue with returning these mostly empty records to the user. 

Recv and recvDeps are created using the same view (vwR_Metadata_for_receivers_recvDeps) so I dont think I can return a record in recv without also having a blank record in recvDeps. 

3. For now, if we can get the motusUserID populated in sg_batches we can deal with this issue in the notification center until the new process is up and running. 

4. If these procs are still being used, they aren't returning the correct information into the DB, so I should either scrap them or fix them.

**Comment by denislepage** [comment] 2018-01-24 23:58
I am pretty sure you will never get the user ID’s for older batches, and I don’t know that it’s worth trying to find them all. They just weren’t collected then, and some of them even pre-dates the notion of a Motus User ID. We should make sure we have them for all new incoming batches though, and perhaps more importantly, a project ID. We should make the process in a way that no receiver file can be processed without being assigned to a project. John has recently asked me to send him a list of users associated with projects. He was presumably trying to resolve some of that(?) for recent batches.

None of the recent batches (>= 114283) seem to have a userID or a projectID. If we had those, we can add the receiver ourselves to the project at the time of the SG data import, as a temporary fix, something I can look into. I’m not sure you’ve ever need to show anything in the notification center once we have our act together on registration. We would take that step sooner once we control the upload. I’ve filed an issue: https://github.com/jbrzusto/motusServer/issues/323

I’m ok with the idea of left join for missing deployments, but the receiver still needs to be at least registered to a project that the user can see to be returned in metadata. The previous view also allowed to return metadata even if the sensors_hash_keys record was missing, but not the new version. Your primary table is now sensors_hash_keys. I don’t think it should be.

I’m ok with removing procs if they are not used, but my point is that we need to find out. Did you search the Java code for any references to them, including the API 1?

git grep “prAPIImportSensor” – “*.*”

returns many references, so before removing them, we need to find out if there is still a use for them.  Getting a list of the entry points that use the procs and asking John to check if he ever use them is the path forward.

**Comment by cjardine-bsc** [comment] 2018-01-25 00:57
That's fine. I just wanted to make sure new batches include MotusUserID. Thanks for logging the issue. I do think it's worth at least asking John whether he has userIDs or projects for the following batches, These they have data but their device's are not registered to any project. 

915 912 487 508 505 772
 
I agree that we won't need anything in the notification center once we have registrations sorted out correctly. As I said, it was an interim solution to try and get these receivers registered to the correct project. I saw your email with script to write to the sensors table based on the projectID in sg_batches. For some reason I had an inkling that the projectID from this table might just be the top 1 projectID the user is registered to, not the actual project that the sensor data should be assigned to (some of the users from these batches are registered to more than one project) but if users select a projectID when they upload data then this is fine. I don't know why I'm thinking it's otherwise, the upload page is currently down so I can't check. There's probably no harm in running that script regardless, especially given I'm not sure that the projectID in sg_batches isn't correct. 

As for vwR_Metadata_for_receivers_recvDeps I thought the API pulled from this table based on deviceID? And then checked accessLevel to validate access. I must be misunderstanding that process. For now, since you're concerned, I've reverted the query in live while I test sandbox. 

Yes, I'm looking into where those prApIImportSensor queries are being used. I understood your point, my comment was meant to indicate that I'll be following up with one of the two outcomes (delete or fix).

**Comment by denislepage** [comment] 2018-02-01 04:15
I checked the database on John's side. There hasn't been any changes to the batches metadata, so I think we have what we have now. There were a few receivers that were unregistered to projects, and we can add those manually for now, and integrate this as part of the import/registration process. That won't solve everything, but that will help a bit. It may still be worth asking John if he has resolved anything that isn't already in the batches table. Most of the recent batches from the last few days have a userID and projectID, but not all. We should check again with John to understand how those happen.

**Comment by cjardine-bsc** [comment] 2018-02-06 17:57
The view has been changed to the below. 

ALTER VIEW [dbo].[vwR_Metadata_for_receivers_recvDeps]
AS

SELECT b.id as deployID, ISNULL(a.project_id,0) as projectID,ISNULL(a.receiverID, c.receiverID) as serno,
ISNULL(a.receiver_type, c.receiver_type) as receiverType,
c.id as deviceID,d.descr as status, b.name, f.name as siteName, b.fixture_type as fixtureType, b.latitude, b.longitude, elevation,
cast(g.is_mobile as tinyint) as isMobile, dbo.datetime2ts(b.dt_start) AS tsStart, dbo.datetime2ts(b.dt_end) AS tsEnd, 
ISNULL(e.accessLevel,0) as accessLevel, ISNULL(e.is_private_sensor, 0) as is_private_sensor
FROM sensors_hash_keys c
FULL OUTER JOIN sensors a on a.receiverID = c.receiverID
LEFT JOIN sensor_deployments b on a.id = b.sensor_id
LEFT JOIN lk_deployment_status d on b.status=d.status 
LEFT JOIN vwProjectsSecurables e on a.project_id = e.project_id AND e.securable = 'receivers_deployments'
LEFT JOIN sensor_sites f on b.site_id = f.id 
LEFT JOIN lk_fixture_type g on b.fixture_type=g.fixture_type

Changes to vwR_Metadata_for_receivers_antDeps aren’t needed since deployments can’t be created for receivers without projects.

**Closed** 2021-01-15 14:07 UTC
Labels: Presumed Resolved
